clear
# add a welcome message?
echo -ne "Today is "; date
echo -e ""; cal ;
uptime

# source the bashrc file
if [ -f $HOME/.bashrc ]; then
  source $HOME/.bashrc
fi
# Add bash completion files, before aliases
if [[ -d $HOME/.bash_completion.d ]]; then
  for i in $(LC_ALL=C command ls "$HOME/.bash_completion.d"); do
    source "$HOME/.bash_completion.d/$i"
  done
fi
unset i

# source aliases
# [[ -f "$HOME/dotfiles/shell/aliases" ]] && source "$HOME/dotfiles/shell/aliases"
source "$HOME/dotfiles/shell/aliases"

# update dotfiles
cd ~/dotfiles && git pull && cd ~/

#set the language
export LC_CTYPE="en_US.UTF-8"

# Reset umask to default
umask 022

# Add a local bin folder to the path
if [[ -d "~/bin" ]]; then
  export PATH="~/bin:$PATH"
fi
# add this thing to the path if it exists
if [[ -d "/usr/local/sbin" ]]; then
  export PATH="$PATH:/usr/local/sbin"
fi


# determine if my phone has been backed up recently
# I had to post about this on Stack Overflow
# https://stackoverflow.com/questions/48575673/how-to-determine-if-a-file-has-been-modified-recently-with-bash-on-mac/48575864#48576193

lastbackup=$(find ~/Library/Application\ Support/MobileSync/Backup/* -mtime -10 -type d -maxdepth 0)

if [[ -z $lastbackup ]]; then
  echo -n "You should back up your iphone!"
fi


# Babushka if you havn't babushka'd in a while.
lastbabushkad=$(find ~/.babushka/logs/* -mtime -7 -type f -maxdepth 0)
if [[ -z lastbabushkad ]]; then
  echo "SORRY< BABUSHKAING"
  # cd ~/.babushka/deps
  # git pull
  # babushka base
fi

mod=$(date -r ~/.babushka/logs/tristansokol\:base +%s)
now=$(date +%s)
days=$(expr \( $now - $mod \) / 86400)
if [ "$days" -gt 7 ]; then
  echo -e "${COLOR_RED} You last babushkad $days days ago ${COLOR_NC}"
  echo -e "${COLOR_RED} babushka tristansokol:base --update ${COLOR_NC}"
else
  echo -e "You last babushkad $days days ago"
fi


#experiment with forcing it to load, since it should be there.
for i in $(LC_ALL=C command ls "$HOME/.bash_completion.d"); do
  source "$HOME/.bash_completion.d/$i"
done
unset i

if [ $BASH_VERSINFO -ge 4 ]; then
  if [[ -n $(which brew) && -f $(brew --prefix)/share/bash-completion/bash_completion ]]; then
    . $(brew --prefix)/share/bash-completion/bash_completion
  fi
elif [ $BASH_VERSINFO -eq 3 ]; then
  if [[ -n $(which brew) && -f $(brew --prefix)/etc/bash_completion ]]; then
    . $(brew --prefix)/etc/bash_completion
  fi
fi

# TODO explore putting this as a prompt command to take advantage of the color hints setting

export GIT_PS1_SHOWUNTRACKEDFILE=true
export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWUPSTREAM=auto
export GIT_PS1_SHOWCOLORHINTS=true


# TODO Add a babushka dep to copy the bash profile and bash rc to a certain spot in my dotfiles repo and then replace them with a different .bashrc and profile that source the bash profile and bashrc in this repo.
