if [ -f $HOME/.bashrc ]; then
        source $HOME/.bashrc
fi

# determine if my phone has been backed up recently
# I had to post about this on Stack Overflow
# https://stackoverflow.com/questions/48575673/how-to-determine-if-a-file-has-been-modified-recently-with-bash-on-mac/48575864#48576193

lastbackup=$(find ~/Library/Application\ Support/MobileSync/Backup/* -mtime -10 -type d -maxdepth 0)

if [[ -z "$lastbackup" ]]; then
  echo "You should back up your iphone!"
fi

# TODO Add a babushka dep to copy the bash profile and bash rc to a certain spot in my dotfiles repo and then replace them with a different .bashrc and profile that source the bash profile and bashrc in this repo.
