#!/bin/sh
.git/hooks/ctags >/dev/null 2>&1 &
### lolcommits hook (begin) ###
LANG="en_US.UTF-8" && PATH="/Users/tristans/.rvm/rubies/ruby-2.3.1/bin:/usr/local/bin:$PATH" && if [ ! -d "$GIT_DIR/rebase-merge" ] && [ "$LOLCOMMITS_CAPTURE_DISABLED" != "true" ]; then lolcommits --capture --animate 4 --fork; fi
###  lolcommits hook (end)  ###
